config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'orders/complete' => "public/orders#complete"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords],  controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    get 'items/new' => "items#new"
    post 'items' => "items#create"
    get 'items' => "items#index"
    get 'items/:id' => "items#show", as: 'item'
    get 'items/:id/edit' => "items#edit", as: 'items_edit'
    patch 'items/:id' => "items#update"
    resources :orders, only:[:show]
  end

 scope module: :public do
    resources :items, only: [:index, :show]
    root to: 'homes#top'
    resources :cart_items, only: [:index, :update, :create, :destroy, :update]
    resources :orders, only: [:index, :new, :show]
    post '/orders/check' => "orders#check"
    post '/orders' => "orders#create", as: 'orders_create'
    delete '/cart_items/destroy_all' => "cart_items#destroy_all"
    get '/customers/my_page' => "customers#show"
    get '/customers/my_page/edit' => "customers#edit"
    patch '/customers/my_page' => "customers#update", as: 'my_page_edit'
    get '/customers/orders' => "orders#index"
    get '/customers/cart_items' => "cart_items#index"
    post '/cart_items/:id' => "cart_items#show"
    get '/customers/withdraw_confirmation' => "customers#withdraw_confirmation", as: 'customers_withdraw_confirmation'
    patch '/customers/withdraw' => "customers#withdraw"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :introduction, presence: true, length: { maximum: 200 }

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def with_tax_price
    (price * 1.1).floor
  end

  has_many :cart_items, dependent: :destroy
  has_many :order_details

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def index
 @items = Item.all
# @item = Item.find(@items)
 @items = @items.page(params[:page])
end

def new
 @item = Item.new
end

def show
 @item = Item.find(params[:id])
 @item_image = Item.new
end

def create
 @item = Item.new(item_params)
 @item.save!
 redirect_to admin_item_path(@item.id)
end

def edit
 @item = Item.find(params[:id])
end

def update
 @item = Item.find(params[:id])
 @item.update(item_params)
 redirect_to admin_items_path
end

private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div clas="container">
  <div class="row">
    <div class="mx-auto">


   <h5 class="col-5 mt-5 alert-secondary mb-5 p-2 text-center">商品編集</h5>

    <body class="m-5">
    <%= form_with model: @item, method: :patch, url: admin_item_path(@item) do |f| %>

    <table class="mb-3 pr-5 center-block">
    <tr>
      <td><label for="inputImage">商品画像</label></td>
      <td><%= f.file_field :image, placeholder: "商品画像", accept: "image/*" %> </td>
    </tr>
    </table>

    <table class="mt-3">
    <tr>
      <td><label for="inputName">商品名</label></td>
      <td><%= f.text_field :name, autofocus: true, id:"@item", placeholder:"商品名" %></td>
    </tr>
    </table>

    <table class="mt-3">
      <tr>
      <td><label for="inputName">商品説明</label></td>
      <td><%= f.text_field :introduction, autofocus: true, id:"inputName", placeholder:"商品説明" %></td>
    </tr>
    </table>

    <table class="mt-3">
      <tr>
      <td><label for="inputName">税抜価格</label></td>
      <td><%= f.text_field :price, autofocus: true, id:"inputName", placeholder:"税抜価格" %>円</td>
    </tr>
    </table>

    <div class="mt-5 p-10 w-15 m-5 p-5">
      <%= f.submit "変更を保存", class: "btn-success p-3 rounded" %>
    </div>

    <% end %>
    </body>
  </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
    <div class="row">
       <table>
            <div class="mt-5 pl-5 alert-secondary col-2 mb-3">
            <h5>商品一覧</h5>
            </div>
       </table>

        <body>
        <table class="my-3 w-50 text-left table table-striped col-12">
            <tr>
                <th class="pl-5">商品ID</th>
                <th class="col-5">商品名</th>
                <th>税抜価格</th>
            </tr>
        </table>

        <% @items.each do |item| %>
        <table class="mt-2 mb-2 w-50 text-left border-bottom col-12 mb-5">
            <tr>
                <td class="pl-5 pt-1 pb-2 col-2"><%= item.id %></td>
                <td class="col-5 text-center"><%= link_to item.name, admin_item_path(item.id) %></td>
                <td class="text-center col-6"><%= item.price %></td>
            </tr>
        </table>
        <% end %>
        </body>

        <div class="col-12">
        <footer class="pl-5 pt-5 w-100 pb-5 text-center mb-5">
         <%= link_to "新規商品登録", admin_items_new_path, class: "btn-success p-3 rounded" %>
        <%= paginate @items %>
        </footer>
        </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div clas="container">
  <div class="row">
    <div class="mx-auto">


   <h5 class="col-5 mt-5 alert-secondary mb-5 p-2 text-center">商品新規登録</h5>

    <body class="m-5">
    <%= form_with model: @item, url: admin_items_path do |f| %>

    <table class="mb-3 pr-5 center-block">
    <tr>
      <td>商品画像</td>
      <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
    </table>

    <table class="mt-3">
    <tr>
      <td>商品名</td>
      <td><%= f.text_field :name %></td>
    </tr>
    </table>

    <table class="mt-3">
      <tr>
      <td>商品説明</td>
      <td><%= f.text_field :introduction %></td>
    </tr>
    </table>

    <table class="mt-3">
      <tr>
      <td>税抜価格</td>
      <td><%= f.number_field :price %>円</td>
    </tr>
    </table>

    <div class="mt-5 p-10">
      <%= f.submit "新規登録", class: "btn-success p-2 rounded" %>
    </div>

    <% end %>
    </body>
  </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-2 mt-5 pl-5 alert-secondary mb-4">
        <h5>商品詳細</h5>
        </div>
    </div>

    <div class="row">
    <table class="mt-5 col-5">
            <p><%= image_tag @item.image, :size =>'400x200' %></p>
    </div>

        <div class="row">
        <div class="col-5 mt-5 ml-5">
            <tr>
                <td>商品名</td>
                <td class="p-1"><%= @item.name %></td>
            </tr>
            <tr>
                <td>商品説明</td>
                <td class="p-1"><%= @item.introduction %></td>
            </tr>
            <tr>
                <td>税抜価格</td>
                <td class="p-1"><%= @item.price %>円</td>
            </tr>
            
            <footer>
                </div><%= link_to "編集する", admin_items_edit_path(@item.id), class: "btn-success p-3 rounded m-5" %></div>
            </footer>
        </div>
        </div>
        </div>
    </table>
    </div>
</div>