config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'orders/complete' => "public/orders#complete"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords],  controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    get 'items/new' => "items#new"
    post 'items' => "items#create"
    get 'items' => "items#index"
    get 'items/:id' => "items#show", as: 'item'
    get 'items/:id/edit' => "items#edit", as: 'items_edit'
    patch 'items/:id' => "items#update"
    resources :orders, only:[:show]
  end

 scope module: :public do
    resources :items, only: [:index, :show]
    root to: 'homes#top'
    resources :cart_items, only: [:index, :update, :create, :destroy, :update]
    resources :orders, only: [:index, :new, :show]
    post '/orders/check' => "orders#check"
    post '/orders' => "orders#create", as: 'orders_create'
    delete '/cart_items/destroy_all' => "cart_items#destroy_all"
    get '/customers/my_page' => "customers#show"
    get '/customers/my_page/edit' => "customers#edit"
    patch '/customers/my_page' => "customers#update", as: 'my_page_edit'
    get '/customers/orders' => "orders#index"
    get '/customers/cart_items' => "cart_items#index"
    post '/cart_items/:id' => "cart_items#show"
    get '/customers/withdraw_confirmation' => "customers#withdraw_confirmation", as: 'customers_withdraw_confirmation'
    patch '/customers/withdraw' => "customers#withdraw"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, dependent: :destroy

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
    @customer = @customers.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.save
    redirect_to edit_admin_customer_path(@customer.id)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path(customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="mt-5 p-1 alert-secondary col-4 text-center">
          <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
          <h5><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h5>
          <% end %>
        </div>
    </div>

    <div class="row">
      <div class="col-12 mt-5">
        <body>
        <%= form_with model: @customer, method: :patch, url: admin_customer_path(@customer) do |f| %>
        <table>
            <tr>
              <td class="w-40 p-2"><label for="inputName">氏名</label></dr>
              <td class="pl-5"><%= f.text_field :last_name, autofocus: true, id:"@customer", placeholder:"氏名" %></td>
            　<td class="pl-5"><%= f.text_field :first_name, autofocus: true, id:"@customer", placeholder:"氏名" %></td>
            </tr>

            <tr>
              <td class="w-40 p-2"><label for="inputName">フリガナ</label></td>
              <td class="pl-5"><%= f.text_field :last_name_kana, autofocus: true, id:"@customer", placeholder:"フリガナ" %></td>
            　<td class="pl-5"><%= f.text_field :first_name_kana, autofocus: true, id:"@customer", placeholder:"フリガナ" %></td>
            </tr>

            <tr>
              <td class="w-40 p-2"><label for="inputName">郵便番号</label></td>
              <td class="pl-5"><%= f.text_field :postal_code, autofocus: true, id:"@customer", placeholder:"郵便番号" %></td>
            </tr>

            <tr>
              <td class="w-40 p-2"><label for="inputName">住所</label></td>
              <td class="pl-5"><%= f.text_field :address, autofocus: true, id:"@customer", placeholder:"住所" %></td>
            </tr>

            <tr>
              <td class="w-40 p-2"><label for="inputName">電話番号</label></td>
              <td class="pl-5"><%= f.text_field :telephone_number, autofocus: true, id:"@customer", placeholder:"電話番号" %></td>
            </tr>

            <tr>
              <td class="w-40 p-2"><label for="inputName">メールアドレス</label></td>
              <td class="pl-5"><%= f.text_field :email, autofocus: true, id:"@customer", placeholder:"メールアドレス" %></td>
            </tr>
        </table>
        <%= f.submit "変更を保存する", class: "btn-success p-3 m-5 rounded" %>
        <% end %>
      <div>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
    <div class="row">
       <table>
            <div class="mt-5 p-1 text-center alert-secondary col-2 mb-3">
            <h5>会員一覧</h5>
            </div>
       </table>

        <body>
        <table class="mt-3 w-50 text-left table table-striped col-12">
            <tr>
                <th class="pl-5">会員ID</th>
                <th class="col-5">氏名</th>
                <th>メールアドレス</th>
            </tr>
        </table>

        <% @customers.each do |customer| %>
        <table class="mt-2 mb-2 w-50 text-left border-top col-12">
            <tr>
                <td class="pl-5 pt-2 pb-2 co1-3"><%= customer.id %></td>
                <td class="col-5 text-center">
                  <%= link_to customer.last_name, admin_customer_path(customer.id) %>
                  <%= link_to customer.first_name, admin_customer_path(customer.id) %>
                </td>
                <td class="text-center col-6"><%= customer.email %></td>
            </tr>
        </table>
        <% end %>
        </body>

        <footer class="pl-5 border-top pt-3 w-50 col-12 pb-5 text-center">
        <%= paginate @customer %>
        </footer>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
       <table>
            <div class="mt-5 p-1 alert-secondary col-4 text-center">
            <h5><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h5>
            </div>
       </table>

        <div class="col-12">

     <body>
        <table class="mt-5 w-50 text-left">
            <tr>
                <td class="pl-5 p-2">会員ID</td>
                <td><%= @customer.id %></td>
            </tr>
            <tr>
                <td class="pl-5 p-2">氏名</td>
                <td><%= @customer.first_name %> <%= @customer.last_name %></td>
            </tr>
            <tr>
                <td class="pl-5 p-2">フリガナ</td>
                <td><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
            </tr>
            <tr>
                <td class="pl-5 p-2">郵便番号</td>
                <td><%= @customer.postal_code %></td>
            </tr>
            <tr>
                <td class="pl-5 p-2">住所</td>
                <td><%= @customer.address %></td>
            </tr>
             <tr>
                <td class="pl-5 p-2">電話番号</td>
                <td><%= @customer.telephone_number %></td>
            </tr>
             <tr>
                <td class="pl-5 p-2">メールアドレス</td>
                <td><%= @customer.email %></td>
            </tr>

        </table>

         <div class="mt-5 p-10 w-15 m-5 p-5">
        <tr>
            <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn-success p-3 rounded" %>
        </tr>
        <tr>
            <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn-success p-3 rounded" %>
        </tr>
         </div>

    </body>

 </div>
</div>