config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'orders/complete' => "public/orders#complete"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords],  controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    get 'items/new' => "items#new"
    post 'items' => "items#create"
    get 'items' => "items#index"
    get 'items/:id' => "items#show", as: 'item'
    get 'items/:id/edit' => "items#edit", as: 'items_edit'
    patch 'items/:id' => "items#update"
    resources :orders, only:[:show]
  end

 scope module: :public do
    resources :items, only: [:index, :show]
    root to: 'homes#top'
    resources :cart_items, only: [:index, :update, :create, :destroy, :update]
    resources :orders, only: [:index, :new, :show]
    post '/orders/check' => "orders#check"
    post '/orders' => "orders#create", as: 'orders_create'
    delete '/cart_items/destroy_all' => "cart_items#destroy_all"
    get '/customers/my_page' => "customers#show"
    get '/customers/my_page/edit' => "customers#edit"
    patch '/customers/my_page' => "customers#update", as: 'my_page_edit'
    get '/customers/orders' => "orders#index"
    get '/customers/cart_items' => "cart_items#index"
    post '/cart_items/:id' => "cart_items#show"
    get '/customers/withdraw_confirmation' => "customers#withdraw_confirmation", as: 'customers_withdraw_confirmation'
    patch '/customers/withdraw' => "customers#withdraw"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    # @order.name = current_customer.last_name + " " + current_customer.first_name
    @order = Order.page(params[:page])
    @sum = 0
  end

  private

  def order_detail_params
    params.require(:order_detail).permit(:payment_method, :customer_id, :total_price, :postage, :address, :post_code, :name)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 alert-secondary text-center">
    <h5>注文履歴一覧</h5>
    </div>
  </div>

  <div class="row">
    <table class="mt-5 col-8">
      <thead>
        <tr>
          <th class="py-3 border alert-secondary">購入日時</th>
          <th class="py-3 border alert-secondary">購入者</th>
          <th class="py-3 border alert-secondary">注文個数</th>
        </tr>
      </thead>

      <% @order.each do |order| %>
      <tbody>
        <tr>
          <td class="py-2 border-top border-bottom"><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M"), admin_order_path(order) %></td>
          <td class="py-2 border-top  border-bottom"><%= order.customer.last_name %><%= order.customer.first_name %></td>
          <% @sum = 0 %>
          <% order.order_details.each do |order_detail| %>
          <% @sum = @sum + order_detail.amount %>
          <% end %>
          <td class="py-2 border-top  border-bottom"><%= @sum %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
    </div>

    <div class="row">
      <table>
       <footer class="pl-5 pt-5 pb-5 mx-auto">
        <%= paginate @order %>
      </footer>
      </table>
    </div>
  </div>