config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'orders/complete' => "public/orders#complete"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords],  controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    get 'items/new' => "items#new"
    post 'items' => "items#create"
    get 'items' => "items#index"
    get 'items/:id' => "items#show", as: 'item'
    get 'items/:id/edit' => "items#edit", as: 'items_edit'
    patch 'items/:id' => "items#update"
    resources :orders, only:[:show]
  end

 scope module: :public do
    resources :items, only: [:index, :show]
    root to: 'homes#top'
    resources :cart_items, only: [:index, :update, :create, :destroy, :update]
    resources :orders, only: [:index, :new, :show]
    post '/orders/check' => "orders#check"
    post '/orders' => "orders#create", as: 'orders_create'
    delete '/cart_items/destroy_all' => "cart_items#destroy_all"
    get '/customers/my_page' => "customers#show"
    get '/customers/my_page/edit' => "customers#edit"
    patch '/customers/my_page' => "customers#update", as: 'my_page_edit'
    get '/customers/orders' => "orders#index"
    get '/customers/cart_items' => "cart_items#index"
    post '/cart_items/:id' => "cart_items#show"
    get '/customers/withdraw_confirmation' => "customers#withdraw_confirmation", as: 'customers_withdraw_confirmation'
    patch '/customers/withdraw' => "customers#withdraw"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :customers
  has_many :order_details

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  def subtotal
    item.with_tax_price * amount
  end

  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, dependent: :destroy

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :introduction, presence: true, length: { maximum: 200 }

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def with_tax_price
    (price * 1.1).floor
  end

  has_many :cart_items, dependent: :destroy
  has_many :order_details

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }

  belongs_to :customer
  has_many :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  def subtotal_order_detail
    price * amount
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
    @customer = @customers.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.save
    redirect_to edit_admin_customer_path(@customer.id)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path(customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    # @order.name = current_customer.last_name + " " + current_customer.first_name
    @order = Order.page(params[:page])
    @sum = 0
  end

  private

  def order_detail_params
    params.require(:order_detail).permit(:payment_method, :customer_id, :total_price, :postage, :address, :post_code, :name)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def index
 @items = Item.all
# @item = Item.find(@items)
 @items = @items.page(params[:page])
end

def new
 @item = Item.new
end

def show
 @item = Item.find(params[:id])
 @item_image = Item.new
end

def create
 @item = Item.new(item_params)
 @item.save!
 redirect_to admin_item_path(@item.id)
end

def edit
 @item = Item.find(params[:id])
end

def update
 @item = Item.find(params[:id])
 @item.update(item_params)
 redirect_to admin_items_path
end

private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

 def show
   @order = Order.find(params[:id])
   @customer = @order.customer
   @sum = 0
 end

 private

def order_params
 params.require(:order).permit(:payment_method, :customer_id, :total_price, :postage, :address, :post_code, :name)
end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  before_action :configure_sign_up_params,only: [:create]

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
  end

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2ff29df84d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <tabele>
          <tr>
            <td>
              <div class="p-3 m-3 h-50">
              <%= link_to "ながのCAKE", root_path, class: "border border-2 rounded py-2 px-5 w-50 ml-5 h2" %>
              </div>
            </td>
          </tr>
      <div class="text-right pr-5">
        <% if admin_signed_in? %>
          <tr>
            <td> <%= link_to "商品一覧", admin_items_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
          <tr>
            <td> <%= link_to "会員一覧", admin_customers_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
          <tr>
            <td> <%= link_to "注文履歴一覧", admin_root_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
          <tr>
            <td> <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
        <% elsif customer_signed_in? %>
          <tr>
            <td><%= link_to "マイページ", customers_my_page_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
          <tr>
            <td><%= link_to "商品一覧", items_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
          <tr>
            <td><%= link_to "カート", cart_items_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
          <tr>
            <td><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
        <% else %>
          <tr>
            <td><%= link_to "新規登録", new_customer_registration_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
          <tr>
            <td><%= link_to "ログイン", new_customer_session_path, class: "border border-2 rounded p-2 m-3" %></td>
          </tr>
        <% end %>
      </div>
        </tabele>
    </header>
      <%= yield %>
  </body>

</html>